[[redirects]]
  from = "/pact_broker/terraform-provider"
  to = "/pact_broker/terraform_provider"
  status = 301

[[redirects]]
  from = "/pact_broker/advanced_topics/webhooks/template_lib"
  to = "/pact_broker/webhooks/template_library"
  status = 301

[[redirects]]
  from = "/pact_broker/advanced_topics/webhooks"
  to = "/pact_broker/webhooks"
  status = 301

[[redirects]]
  from = "/consumer_version_selectors"
  to = "/pact_broker/advanced_topics/consumer_version_selectors"
  status = 301

[[redirects]]
  from = "/pending"
  to = "/pact_broker/advanced_topics/pending_pacts"
  status = 301

[[redirects]]
  from = "/wip"
  to = "/pact_broker/advanced_topics/wip_pacts"
  status = 301
