name: Sync Pact docs

on:
  repository_dispatch:
    types: [pact-js-docs-updated, pact-jvm-docs-updated, pact-python-docs-updated]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - run: gem install bundler -v 2.0.2 && bundle install

    - name: Sync Pact JS docs
      run: bundle exec ruby scripts/sync/pact_js.rb && echo '::set-env name=COMMIT_MESSAGE::synced pact-js docs'
      if: github.event.action == 'pact-js-docs-updated'

    - name: Sync Pact JVM docs
      run: bundle exec ruby scripts/sync/pact_jvm.rb && echo '::set-env name=COMMIT_MESSAGE::synced pact-jvm docs'
      if: github.event.action == 'pact-jvm-docs-updated'

    - name: Sync Pact Python docs
      run: bundle exec ruby scripts/sync/pact_python.rb && echo '::set-env name=COMMIT_MESSAGE::synced pact-python docs'
      if: github.event.action == 'pact-python-docs-updated'

    - name: Commit and push changes
      uses: EndBug/add-and-commit@v4
      with:
        add: 'docs/implementation_guides'
        author_name: Github Action
        author_email: docs@pact.io
        message: 'chore: ${{ env.COMMIT_MESSAGE }}'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
