name: Update Pact JS docs

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: '2.6'
    - run: gem install bundler -v 2.0.2
    - run: bundle install
    - run: ruby scripts/sync/pact_js.rb

    - uses: EndBug/add-and-commit@v4
      with:
        add: 'docs/implementation_guides/javascript'
        author_name: Github Action
        author_email: beth@bethesque.com
        message: 'chore: updated javascript documentation from pact-js repository'
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }} # Leave this line unchanged
